"""
Base configuration for AS-Mamba.
This file defines the core architecture and training parameters.
"""

from yacs.config import CfgNode as CN

_CN = CN()

##############  ↓  AS-MAMBA Architecture  ↓  ##############
_CN.AS_MAMBA = CN()

# Resolution settings (coarse_scale, fine_scale)
_CN.AS_MAMBA.RESOLUTION = (8, 2)
_CN.AS_MAMBA.FINE_WINDOW_SIZE = 5

# Model dimensions
_CN.AS_MAMBA.COARSE = CN()
_CN.AS_MAMBA.COARSE.D_MODEL = 256

_CN.AS_MAMBA.FINE = CN()
_CN.AS_MAMBA.FINE.D_MODEL = 64

# AS-Mamba specific parameters
_CN.AS_MAMBA.N_BLOCKS = 3  # Number of AS-Mamba blocks
_CN.AS_MAMBA.D_GEOM = 64   # Geometric feature dimension
_CN.AS_MAMBA.USE_KAN_FLOW = False  # Use KAN for flow prediction
_CN.AS_MAMBA.GLOBAL_DEPTH = 4  # Depth of global Mamba path
_CN.AS_MAMBA.LOCAL_DEPTH = 4   # Depth of local Mamba path

# Matching configuration
_CN.AS_MAMBA.MATCH_COARSE = CN()
_CN.AS_MAMBA.MATCH_COARSE.USE_SM = True
_CN.AS_MAMBA.MATCH_COARSE.THR = 0.2
_CN.AS_MAMBA.MATCH_COARSE.BORDER_RM = 2
_CN.AS_MAMBA.MATCH_COARSE.DSMAX_TEMPERATURE = 0.1
_CN.AS_MAMBA.MATCH_COARSE.SKH_ITERS = 3
_CN.AS_MAMBA.MATCH_COARSE.TRAIN_COARSE_PERCENT = 0.3
_CN.AS_MAMBA.MATCH_COARSE.TRAIN_PAD_NUM_GT_MIN = 200
_CN.AS_MAMBA.MATCH_COARSE.INFERENCE = False

_CN.AS_MAMBA.FINE = CN()
_CN.AS_MAMBA.FINE.D_MODEL = 64
_CN.AS_MAMBA.FINE.INFERENCE = False
_CN.AS_MAMBA.FINE.DSMAX_TEMPERATURE = 0.1
_CN.AS_MAMBA.FINE.THR = 0.1

# Loss weights
_CN.AS_MAMBA.LOSS = CN()
_CN.AS_MAMBA.LOSS.FLOW_WEIGHT = 0.5      # CRITICAL for adaptive spans
_CN.AS_MAMBA.LOSS.COARSE_WEIGHT = 1.0
_CN.AS_MAMBA.LOSS.FINE_WEIGHT = 1.0
_CN.AS_MAMBA.LOSS.EPIPOLAR_WEIGHT = 0.1
_CN.AS_MAMBA.LOSS.MULTISCALE_WEIGHT = 0.05
_CN.AS_MAMBA.LOSS.FOCAL_ALPHA = 0.25
_CN.AS_MAMBA.LOSS.FOCAL_GAMMA = 2.0
_CN.AS_MAMBA.LOSS.POS_WEIGHT = 1.0
_CN.AS_MAMBA.LOSS.NEG_WEIGHT = 1.0

# Performance
_CN.AS_MAMBA.MP = False  # Mixed precision
_CN.AS_MAMBA.EVAL_TIMES = 1

##############  Dataset  ##############
_CN.DATASET = CN()
_CN.DATASET.TRAINVAL_DATA_SOURCE = None
_CN.DATASET.TEST_DATA_SOURCE = None
_CN.DATASET.MIN_OVERLAP_SCORE_TRAIN = 0.4
_CN.DATASET.MIN_OVERLAP_SCORE_TEST = 0.0
_CN.DATASET.AUGMENTATION_TYPE = None
_CN.DATASET.CORR_TH = 5
_CN.DATASET.MGDPT_IMG_RESIZE = 832
_CN.DATASET.MGDPT_IMG_PAD = True
_CN.DATASET.MGDPT_DEPTH_PAD = True
_CN.DATASET.MGDPT_DF = 8

##############  Trainer  ##############
_CN.TRAINER = CN()
_CN.TRAINER.WORLD_SIZE = 1
_CN.TRAINER.CANONICAL_BS = 2
_CN.TRAINER.CANONICAL_LR = 1e-4
_CN.TRAINER.SCALING = None
_CN.TRAINER.FIND_LR = False

# Optimizer
_CN.TRAINER.OPTIMIZER = "adamw"
_CN.TRAINER.TRUE_LR = None
_CN.TRAINER.ADAM_DECAY = 0.
_CN.TRAINER.ADAMW_DECAY = 0.1

# Warm-up
_CN.TRAINER.WARMUP_TYPE = 'linear'
_CN.TRAINER.WARMUP_RATIO = 0.
_CN.TRAINER.WARMUP_STEP = 4800

# Learning rate scheduler
_CN.TRAINER.SCHEDULER = 'CosineAnnealing'
_CN.TRAINER.SCHEDULER_INTERVAL = 'epoch'
_CN.TRAINER.MSLR_MILESTONES = [3, 6, 9, 12]
_CN.TRAINER.MSLR_GAMMA = 0.5
_CN.TRAINER.COSA_TMAX = 30
_CN.TRAINER.ELR_GAMMA = 0.999992

# Training
_CN.TRAINER.GRADIENT_CLIPPING = 0.5
_CN.TRAINER.SEED = 66

# Evaluation
_CN.TRAINER.N_VAL_PAIRS_TO_PLOT = 32
_CN.TRAINER.PLOT_MODE = 'evaluation'
_CN.TRAINER.PLOT_MATCHES_ALPHA = 'dynamic'
_CN.TRAINER.EPI_ERR_THR = 1e-4
_CN.TRAINER.POSE_GEO_MODEL = 'E'
_CN.TRAINER.POSE_ESTIMATION_METHOD = 'LO-RANSAC'
_CN.TRAINER.RANSAC_PIXEL_THR = 0.5
_CN.TRAINER.RANSAC_CONF = 0.99999
_CN.TRAINER.RANSAC_MAX_ITERS = 10000
_CN.TRAINER.USE_MAGSACPP = False

# Data sampler
_CN.TRAINER.DATA_SAMPLER = 'scene_balance'
_CN.TRAINER.N_SAMPLES_PER_SUBSET = 200
_CN.TRAINER.SB_SUBSET_SAMPLE_REPLACEMENT = True
_CN.TRAINER.SB_SUBSET_SHUFFLE = True
_CN.TRAINER.SB_REPEAT = 1

cfg = _CN